name: newsapp_ar
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.4.1
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  share: ^0.6.5+4
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
